# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 11:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0002_auto_20161016_2211'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitAllocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('c', 'Coordinator'), ('l', 'Lecturer'), ('t', 'Tutor')], max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='unit',
            name='coordinator',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='title',
            field=models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Ms', 'Ms'), ('Miss', 'Miss'), ('Prof', 'Prof'), ('Dr', 'Dr')], max_length=32),
        ),
        migrations.AddField(
            model_name='unitallocation',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LMS.Teacher'),
        ),
        migrations.AddField(
            model_name='unitallocation',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LMS.Unit'),
        ),
        migrations.AddField(
            model_name='unit',
            name='staff',
            field=models.ManyToManyField(through='LMS.UnitAllocation', to='LMS.Teacher'),
        ),
    ]
