# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 18:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0003_auto_20161017_2229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('file', models.FileField(upload_to='')),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LMS.Unit')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LMS.Teacher')),
            ],
        ),
    ]
