# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0006_student_enrolled_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='enrolled_unit',
            field=models.ManyToManyField(blank=True, to='LMS.Unit'),
        ),
    ]
