# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0007_auto_20161019_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentfile',
            name='file',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
