# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0009_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='code',
            field=models.CharField(default='ELEC1234', max_length=16),
            preserve_default=False,
        ),
    ]
