# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0010_unit_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='type',
            field=models.CharField(choices=[('l', 'Lecture'), ('t', 'Tutorial'), ('b', 'Laboratory')], max_length=1),
        ),
    ]
