# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 17:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0011_auto_20161020_0624'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark_assignment', models.FloatField(default=0)),
                ('mark_quiz', models.FloatField(default=0)),
                ('mark_presentation', models.FloatField(default=0)),
                ('mark_mid_exam', models.FloatField(default=0)),
                ('mark_final_exam', models.FloatField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LMS.Student')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LMS.Unit')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.ManyToManyField(blank=True, related_name='grade_record', through='LMS.GradeRecord', to='LMS.Unit'),
        ),
    ]
