# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0012_auto_20161021_0409'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='mark_assignment',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='unit',
            name='mark_final_exam',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='unit',
            name='mark_mid_exam',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='unit',
            name='mark_presentation',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='unit',
            name='mark_quiz',
            field=models.FloatField(default=0),
        ),
    ]
