# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 18:33
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0013_auto_20161021_0411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graderecord',
            name='mark_assignment',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='graderecord',
            name='mark_final_exam',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='graderecord',
            name='mark_mid_exam',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='graderecord',
            name='mark_presentation',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='graderecord',
            name='mark_quiz',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='unit',
            name='mark_assignment',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='unit',
            name='mark_final_exam',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='unit',
            name='mark_mid_exam',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='unit',
            name='mark_presentation',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='unit',
            name='mark_quiz',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
